### ISSUE TITLE
Check the MonDO overnight lookup

### ISSUE THREAD

**Issue by courtneythaxton** [clingen-data-model/clingen-gene-tracker#13]
Hi @yugen I got about 70 emails last night indicating that the MonDO IDs for several records were not in the correct format. However, when I checked several of these the MonDO ID was correct. I also got an email from Erin Riggs and Taylor Bingaman with the same issue.

**Comment by yugen** [comment]
@courtneythaxton I've looked into this and I'm unable to reproduce the problem.  My best guess is that something happened on then side of MonDO's API last night.
