### ISSUE TITLE
Bug in Gene Tracker and updating status manually

### ISSUE THREAD

**Issue by courtneythaxton** [clingen-data-model/clingen-gene-tracker#20]
@yugen I was trying to update some statuses of gene records manually and found that if I wanted to add the "publish" status, it would not work until I tried 3 times. 

The first trying to add, it duplicated the "provisional" status date already shown.
The 2nd time trying to add, it duplicated the "approved" status date already shown.
Finally on the 3rd try I got published.

I would like to call this the goldilocks bug :)

@courtneythaxton

**Comment by yugen** [comment]
@courtneythaxton Thanks for finding this and letting me know.  I've fixed the issue and the changes should be reflected on both demo and production.

**Comment by courtneythaxton** [comment]
Thanks @yugen! glad goldilocks has been fixed!
