### ISSUE TITLE
As a coordinator I'd like to submit a list of gene symbols and see all of the curations that exist for that gene and the expert panels involved.

### ISSUE THREAD

**Issue by yugen** [clingen-data-model/clingen-gene-tracker#27]
Acceptance Criteria
* List should include 
  * Expert Panel
  * Gene
  * Current status and date
  * MonDO ID
  * Current classification and date
* User should be able to download CSV version of results.

**Comment by yugen** [comment]
@courtneythaxton My first pass at this is done and ready for testing on demo.   If you go to clingen.sirs.unc.edu and login, you'll see 'bulk lookup' in the top menu.  If you click on that you can either enter gene symbols in by hand or upload a csv with one column of gene symbols.

Let me know if there are changes or improvements you'd like to see.

**Comment by courtneythaxton** [comment]
@yugen, I took a look at this and it looks good to me. I think it clearly defines out information on the the statuses, and this is another reason/ impetus to get the coordinators to update all past or older records.
