### ISSUE TITLE
As a coordinator I would like notifications sent weekly for GCI records from the StreamingService that don't match an existing GT curation in my expert panel

### ISSUE THREAD

**Issue by yugen** [clingen-data-model/clingen-gene-tracker#30]

**Comment by yugen** [comment]
@courtneythaxton I have a few questions about how to handle these unmatched GCI records:
1. What should we do when an unmatched gci gene/disease record doesn't have an affiliation?
2. What should we do when it has an affiliation, but that affiliation isn't linked to an expert panel?
3. What should we do when it has an affiliation linked to an expert panel, but the panel doesn't have any coordinators?
4. What should this notification say?  Currently I have it saying:
> We received info from the GCI about gene-disease records we cannot match against the GeneTracker:

  Followed by a list of links to the GCI records that could not be matched for a particular affiliation.

**Comment by courtneythaxton** [comment]
Hi TJ,

Great question!


  1.  These would be considered “unaffiliated” and they cannot be published to the ClinGen website. I think for the time being, I would ignore these records, as if someone has interest in this curation record, they would need to transfer the record to an affiliation, and after that occurs, we should get a message once updated with curation progress.
  2.  Could you send an alert/ email to me (admin) to review the records?
  3.  Same as above, as this means I did not add a coordinator, which I should correct
  4.  See below:

Mock up email for alert:

Hi,
We have received data from the GCI about a gene-disease relationship that may be of interest or associated with your group, however at this time the data does not match our current records. Please look over the following records and if they happen to belong to your group, please consider updating the information (e.g. Affiliation, MonDO ID, etc) to allow optimized  automation of future updates. If you have any questions, please contact us at clingentrackerhelp@unc.edu

Best,
ClinGen Gene Tracker Team

What do you think of this email?

**Comment by yugen** [comment]
@courtneythaxton I think that email looks good.  The only thing to keep in mind is that we're now sending a single weekly digest of notifications instead of individual emails so we should probably leave out the salutation, and signature.

**Comment by courtneythaxton** [comment]
@yugen sounds good to leave out the signature and salutations!

**Comment by courtneythaxton** [comment]
@yugen, I am getting emails only once a week, so this seems to be working. Great work!
