### ISSUE TITLE
Update search to include HGNC symbol and other IDs

### ISSUE THREAD

**Issue by courtneythaxton** [clingen-data-model/clingen-gene-tracker#6]
It would be nice to expand the search bar on the dashboard to allow for searching using the IDs we are importing, including HGNC, MONDO, and OMIM

**Comment by yugen** [comment]
@courtneythaxton Curation list will now search against hgnc_id, mondo_id, and phenotype mim_number (we don't currently keep mim_numbers for genes).

**Comment by courtneythaxton** [comment]
@yugen I tested the MonDO ID and it worked, specifically I used the ID of MONDO:0000591. 

When I tried HGNC ID, I used hgnc:9080 and it did not work. I also tried hgnc_9080, HGNC:9080, and HGNC_9080, and those did not work either.

I then used a MIM# for the gene PLN, 609909, and this worked as is.

**Comment by yugen** [comment]
Oops.  Search was not expecting the 'hgnc:' prefix.  Fixed and deployed.

**Comment by courtneythaxton** [comment]
thanks @yugen
