### ISSUE TITLE
Restructure rationale.

### ISSUE THREAD

**Issue by yugen** [clingen-data-model/clingen-gene-tracker#69]
User should be able to add one or more rationales to a precuration record including the following information:
* Rationale type
* Source (PMID or URL)
* Notes

User should also be able to continue to add general notes for rationale.

**Comment by yugen** [comment]
@courtneythaxton We can close this issue because the GC small group decided there wasn't a good reason to change the existing structure, correct?

**Comment by courtneythaxton** [comment]
@yugen Yes, we can close this!
