### ISSUE TITLE
Paging through sorted lists

### ISSUE THREAD

**Issue by marinadistefano** [clingen-data-model/clingen-gene-tracker#9]
When I am on my dashboard or at the entire gene list (in Chrome) if I search for a GCEP to sort the list, I cannot get past the first page of results. It automatically cycles me back to the first page when I try to click the individual page number or the next button.

**Comment by yugen** [comment]
Thanks for bring this to my attention @marinadistefano. I've identified the problem and resolved the issue.  You should see the correct behavior now.

**Comment by marinadistefano** [comment]
Thank you! Looks to be working now.
